--- #YAML:1.0
name:                Filter-Simple
version:             0.83
abstract:            Simplified source filtering
license:             perl
author:              
    - Damian Conway
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Filter::Util::Call:            0
    Text::Balanced:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
